apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mainpage-deployment
  labels:
    app: mainpage-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mainpage-app
      version: v1
  template:
    metadata:
      labels:
        app: mainpage-app
        version: v1
    spec:
      containers:
      - name: controller
        image: python:3.5
        command: ["python", "/pycode/mainpage.py"]
        volumeMounts:
        - name: pycode
          mountPath: /pycode
      volumes:
      - name: pycode
        configMap:
          name: pycode-mainpage
---
apiVersion: v1
kind: Service
metadata:
  name: mainpage-svc
spec:
  selector:
    app: mainpage-app
  ports:
  - port: 8081